-- Create and load all 5 tables

-- ADLS Table
CREATE TABLE adls_pds2019 (
    crf VARCHAR,
    SUBJID VARCHAR,
    VISITDY DOUBLE,
    VISIT VARCHAR,
    LSCAT VARCHAR,
    LSNEW VARCHAR,
    LSSLD DOUBLE,
    LSLD DOUBLE,
    LSSITE VARCHAR,
    LSNEWANY VARCHAR,
    LSREADER VARCHAR,
    LSTYPE VARCHAR,
    protocol_id VARCHAR
);
COPY adls_pds2019 (SUBJID, VISITDY, VISIT, LSCAT, LSNEW, LSSLD, LSLD, LSSITE, LSNEWANY, LSREADER, LSTYPE) 
FROM '/Users/nathan/clinical-trial-data-review/csv_from_sas/20050203/adls_pds2019.csv' (HEADER);
UPDATE adls_pds2019 SET crf = 'ADLS_PDS2019', protocol_id = '20050203';

-- ADPM Table
CREATE TABLE adpm_pds2019 (
    crf VARCHAR,
    SUBJID VARCHAR,
    VISIT VARCHAR,
    VISITDY DOUBLE,
    WEIGHT DOUBLE,
    protocol_id VARCHAR
);
COPY adpm_pds2019 (SUBJID, VISIT, VISITDY, WEIGHT) 
FROM '/Users/nathan/clinical-trial-data-review/csv_from_sas/20050203/adpm_pds2019.csv' (HEADER);
UPDATE adpm_pds2019 SET crf = 'ADPM_PDS2019', protocol_id = '20050203';

-- ADRSP Table
CREATE TABLE adrsp_pds2019 (
    crf VARCHAR,
    SUBJID VARCHAR,
    RSRESP VARCHAR,
    VISITDY DOUBLE,
    VISIT VARCHAR,
    RSCONFYN VARCHAR,
    RSTRESP VARCHAR,
    RSNTRESP VARCHAR,
    RSNEW VARCHAR,
    RSREADER VARCHAR,
    protocol_id VARCHAR
);
COPY adrsp_pds2019 (SUBJID, RSRESP, VISITDY, VISIT, RSCONFYN, RSTRESP, RSNTRESP, RSNEW, RSREADER) 
FROM '/Users/nathan/clinical-trial-data-review/csv_from_sas/20050203/adrsp_pds2019.csv' (HEADER);
UPDATE adrsp_pds2019 SET crf = 'ADRSP_PDS2019', protocol_id = '20050203';

-- ADSL Table
CREATE TABLE adsl_pds2019 (
    crf VARCHAR,
    SUBJID VARCHAR,
    TRT VARCHAR,
    ATRT VARCHAR,
    PRSURG VARCHAR,
    DTHDY DOUBLE,
    DTH DOUBLE,
    PFSDYCR DOUBLE,
    PFSCR DOUBLE,
    LIVERMET VARCHAR,
    DIAGMONS DOUBLE,
    AGE DOUBLE,
    SEX VARCHAR,
    B_WEIGHT DOUBLE,
    B_HEIGHT DOUBLE,
    RACE VARCHAR,
    B_ECOG VARCHAR,
    HISSUBTY VARCHAR,
    B_METANM DOUBLE,
    DIAGTYPE VARCHAR,
    protocol_id VARCHAR
);
COPY adsl_pds2019 (SUBJID, TRT, ATRT, PRSURG, DTHDY, DTH, PFSDYCR, PFSCR, LIVERMET, DIAGMONS, AGE, SEX, B_WEIGHT, B_HEIGHT, RACE, B_ECOG, HISSUBTY, B_METANM, DIAGTYPE) 
FROM '/Users/nathan/clinical-trial-data-review/csv_from_sas/20050203/adsl_pds2019.csv' (HEADER);
UPDATE adsl_pds2019 SET crf = 'ADSL_PDS2019', protocol_id = '20050203';

-- BIOMARK Table
CREATE TABLE biomark_pds2019 (
    crf VARCHAR,
    SUBJID VARCHAR,
    BMMTNM1 VARCHAR,
    BMMTR1 VARCHAR,
    BMMTNM2 VARCHAR,
    BMMTR2 VARCHAR,
    BMMTNM3 VARCHAR,
    BMMTR3 VARCHAR,
    BMMTNM4 VARCHAR,
    BMMTR4 VARCHAR,
    BMMTNM5 VARCHAR,
    BMMTR5 VARCHAR,
    BMMTNM6 VARCHAR,
    BMMTR6 VARCHAR,
    BMMTNM7 VARCHAR,
    BMMTR7 VARCHAR,
    BMMTNM15 VARCHAR,
    BMMTR15 VARCHAR,
    BMMTNM16 VARCHAR,
    BMMTR16 VARCHAR,
    protocol_id VARCHAR
);
COPY biomark_pds2019 (SUBJID, BMMTNM1, BMMTR1, BMMTNM2, BMMTR2, BMMTNM3, BMMTR3, BMMTNM4, BMMTR4, BMMTNM5, BMMTR5, BMMTNM6, BMMTR6, BMMTNM7, BMMTR7, BMMTNM15, BMMTR15, BMMTNM16, BMMTR16) 
FROM '/Users/nathan/clinical-trial-data-review/csv_from_sas/20050203/biomark_pds2019.csv' (HEADER);
UPDATE biomark_pds2019 SET crf = 'BIOMARK_PDS2019', protocol_id = '20050203';

